---
title: Amerifit Fitness
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
description: Amerifit is a gym in the south hills of Pittsburgh, PA. We offer a variety
  of equipment, fitness classes, and personalized training to our members.
baseurl: ''
url: https://amerifitfitnessclub.com
theme: minima
plugins:
- jekyll-feed
source: "./src"
