title: Amerifit Fitness
description: >- # this means to ignore newlines until "baseurl:"
  Amerifit is a gym in the south hills of Pittsburgh, PA. We offer a variety
  of equipment, fitness classes, and personalized training to our members.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://amerifitfitnessclub.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

source: ./src
